// Generated by CoffeeScript 1.7.1
var getCookingIngredientList;

getCookingIngredientList = function(recipeIds) {
  recipeIds = JSON.parse(recipeIds);
  $.ajax({
    type: "GET",
    url: "http://54.178.135.71:8080/CookIEServer/list_ingredient",
    dataType: "application/json",
    data: {
      recipes: recipeIds
    },
    timeout: 10000,
    success: function(data) {
      data = JSON.parse(data);
      console.log('[SUCCESS]fetch ing. list for recipes ##{recipeIds}');
      console.log(data);
      return void 0;
    },
    error: function(data, status) {
      console.log("[ERROR]fetch ing. list for recipes #" + recipeIds);
      return void 0;
    }
  });
  return void 0;
};
