// Generated by CoffeeScript 1.7.1
var lastId, lastQuery, search, searchAjaxd, showSearchResult;

lastId = -1;

searchAjaxd = 0;

lastQuery = '\n';

$(document).ready(function() {
  $("#SearchBar").keyup(function() {
    var query;
    console.log("searchbar keyup");
    clearTimeout(lastId);
    query = $("#SearchBar").text();
    if (query !== lastQuery) {
      searchAjaxd = 0;
      if (query === "") {
        $("#SearchBar").html("<i>Search for recipes, food ingredients ...</i>");
      }
      return void 0;
    }
    lastId = setTimeout(function(query) {
      search(query, searchAjaxd);
      return void 0;
    }, 1500);
    lastQuery = query;
    return void 0;
  });
  return void 0;
});

search = function(query, times) {
  $.ajax({
    type: "GET",
    url: 'http://140.114.195.58:8080/CookIEServer/discover_recipelists',
    dataType: 'jsonp',
    crossDomain: true,
    data: {
      'query': query,
      'times': searchAjaxd
    },
    jsonp: false,
    timeout: 10000,
    success: function(data) {
      console.log("[SUCCESS]search");
      console.log(data);
      showSearchResult(data);
      searchAjaxd++;
      return void 0;
    },
    error: function(data, status) {
      console.log("[ERROR]search: " + status);
      return void 0;
    }
  });
  return void 0;
};

showSearchResult = function(data) {
  if (data.length === 0) {
    $("#SearchBar").html("<i>No results. Search with another query?</i>");
    return void 0;
  }
  if (searchAjaxd) {
    return void 0;
  }
};
