// Generated by CoffeeScript 1.7.1
var getPopularRecipes, recipeAjaxd;

recipeAjaxd = 0;

$(document).ready(function() {
  addInfiniteScroll($('#main_Popular_Recipes'), 3000, function() {
    return getPopularRecipes(recipeAjaxd);
  });
  return void 0;
});

getPopularRecipes = function(times) {
  $.ajax({
    type: "GET",
    url: 'http://54.178.135.71:8080/CookIEServer/discover_recipes',
    dataType: 'jsonp',
    crossDomain: true,
    data: {
      'type': 'popular',
      'times': times
    },
    jsonp: false,
    timeout: 10000,
    success: function(data) {
      var scope, scrollerList;
      console.log("[SUCCESS]fetch popular recipes");
      console.log(data);
      recipeAjaxd++;
      scrollerList = $('#main_Popular_Recipes').scroller();
      scrollerList.clearInfinite();
      if (data.length === 0) {
        $("#main_Popular_Recipes").find("#infinite").text("No more recipes");
        recipeAjaxd--;
        return void 0;
      }
      scope = $("#main_Popular_Recipes");
      appendRecipeResult(scope, data);
      return void 0;
    },
    error: function(data, status) {
      var scrollerList;
      console.log("[ERROR]fetch popular recipes: " + status);
      console.log(data);
      $("#main_Popular_Recipes").find("#infinite").text("Load More");
      scrollerList = $('#main_Popular_Recipes').scroller();
      scrollerList.clearInfinite();
      return void 0;
    }
  });
  return void 0;
};
