// Generated by CoffeeScript 1.7.1
var getMenuContent, loadMenuContent;

getMenuContent = function(scope, menuId) {
  console.log("fetch menu#" + menuId);
  return $.ajax({
    type: 'GET',
    url: 'http://54.178.135.71:8080/CookIEServer/recipelist',
    dataType: 'jsonp',
    crossDomain: true,
    data: {
      'list_id': menuId
    },
    jsonp: false,
    timeout: 10000,
    success: function(data) {
      console.log("[SUCCESS]fetch menu #" + menuId);
      console.log(data);
      setTimeout(loadMenuContent(scope, data), 1000);
      return void 0;
    },
    error: function(data, status) {
      console.log("[ERROR]fetch recipe #" + recipeId);
      console.log(data);
      return void 0;
    }
  });
};

loadMenuContent = function(scope, data) {
  console.log("load for scope: " + scope[0].id);
  return void 0;
};
