// Generated by CoffeeScript 1.7.1
var appendKitchenRecipeList, getKitchenRecipes, kitchenRecipeAjaxd, lastId;

kitchenRecipeAjaxd = 0;

lastId = -1;

$(document).ready(function() {
  var scrollerList;
  scrollerList = $('#main_Kitchen_Recipes').scroller();
  scrollerList.addInfinite();
  $.bind(scrollerList, "infinite-scroll", function() {
    var self;
    console.log("kitchen recipe infinite-scroll");
    self = this;
    $("#main_Kitchen_Recipes").find("#infinite").text("Loading...");
    scrollerList.addInfinite();
    clearTimeout(lastId);
    lastId = setTimeout(function() {
      return getKitchenRecipes(kitchenRecipeAjaxd, self);
    }, 3000);
    return void 0;
  });
  return void 0;
});

getKitchenRecipes = function(times, scrollObj) {
  $.ajax({
    type: "GET",
    url: 'http://140.114.195.58:8080/CookIEServer/discover_recipes',
    dataType: 'jsonp',
    crossDomain: true,
    data: {
      'type': 'popular',
      'times': times
    },
    jsonp: false,
    timeout: 10000,
    success: function(data) {
      console.log("[SUCCESS]fetch kitchen recipes");
      console.log(data);
      appendKitchenRecipeList(data, scrollObj);
      kitchenRecipeAjaxd++;
      return void 0;
    },
    error: function(data, status) {
      console.log("[ERROR]fetch kitchen recipes: " + status);
      console.log(data);
      $("#main_Kitchen_Recipes").find("#infinite").text("Load More");
      scrollObj.clearInfinite();
      return void 0;
    }
  });
  return void 0;
};

appendKitchenRecipeList = function(data, scrollObj) {
  var count, html, id, name, rating, recipe, recipeList, url, _i, _len;
  if (data.length === 0) {
    $("#main_Kitchen_Recipes").find("#infinite").text("No more recipes");
    scrollObj.clearInfinite();
    kitchenRecipeAjaxd--;
    return 1;
  }
  if (data.length % 2) {
    data.length--;
  }
  recipeList = $('#KitchenRecipeList');
  count = 0;
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    recipe = data[_i];
    html = '';
    id = recipe.recipe_id;
    name = recipe.name;
    rating = recipe.rating;
    url = recipe.imageUrl;
    url = 'img/love.jpg';
    if (count % 2 === 0) {
      html += '<div class="recipe_list_row list_row_left" id="KitchenRecipe' + id + '">';
    } else {
      html += '<div class="recipe_list_row list_row_right" id="KitchenRecipe' + id + '">';
    }
    html += '<img class="recipe_img" src="' + url + '">';
    html += '<div class="recipe_title">' + name + '</div>';
    html += '<div class="icon star recipe_rating">' + rating + '</div>';
    html += '</div>';
    recipeList.append(html);
    count++;
  }
  recipeList.find("#bottomBar").remove();
  recipeList.append('<div id="bottomBar" style="display:block;height:0;clear:both;">&nbsp;</div>');
  $("#main_Kitchen_Recipes").find("#infinite").text("Load More");
  scrollObj.clearInfinite();
  return void 0;
};
