// Generated by CoffeeScript 1.7.1
var addInfiniteScroll, appendMenuResult, appendRecipeResult, initSelectBtn, lastId, search, searchAjaxd;

lastId = -1;

searchAjaxd = 0;

$(document).ready(function() {
  initSelectBtn();
  $("#SearchBar").keyup(function() {
    var lastQuery, query, scrollerList;
    console.log("searchbar keyup");
    scrollerList = $('#main_Kitchen_Menus').scroller();
    scrollerList.clearInfinite();
    clearTimeout(lastId);
    query = $("#SearchBar")[0].value;
    if (query === "") {
      searchAjaxd = 0;
      $("#main_Search").find("#infinite").html("<i>Search for recipes, food ingredients ...</i>");
      return void 0;
    }
    $("#main_Search").find("#infinite").text("Searching...");
    lastId = setTimeout(function() {
      search(query, searchAjaxd);
      return void 0;
    }, 1500);
    lastQuery = query;
    return void 0;
  });
  return void 0;
});

initSelectBtn = function() {
  return $("#SearchSelectTab").children().each(function() {
    $(this).on("click", function() {
      var other;
      if ($(this).hasClass('orange')) {
        return void 0;
      }
      other = $(this).siblings()[0];
      $(other).removeClass('orange');
      $(this).addClass('orange');
      console.log("search tab switch");
      searchAjaxd = 0;
      $("#main_Search").find("#Results").html("");
      $("#main_Search").find("#infinite").html("<i>Search for recipes, food ingredients ...</i>");
      return $("#SearchBar").trigger("keyup");
    });
    return void 0;
  });
};

search = function(query, times) {
  var type, url;
  if ($("#SearchSelectTab").find('a').hasClass('orange')) {
    type = 0;
    url = 'http://140.114.195.58:8080/CookIEServer/discover_recipes';
  } else {
    type = 1;
    url = 'http://140.114.195.58:8080/CookIEServer/discover_recipelists';
  }
  $.ajax({
    type: "GET",
    url: url,
    dataType: 'jsonp',
    crossDomain: true,
    data: {
      'type': 'search',
      'name': query,
      'times': searchAjaxd
    },
    jsonp: false,
    timeout: 10000,
    success: function(data) {
      var scope, scrollerList;
      console.log("[SUCCESS]search");
      console.log(data);
      scrollerList = $("#main_Search").scroller();
      scrollerList.clearInfinite();
      if (data.length === 0) {
        $("#main_Search").find("#infinite").html("<i>No more results.</i>");
        searchAjaxd--;
        return void 0;
      }
      if (searchAjaxd === 0) {
        addInfiniteScroll();
      }
      scope = $("#main_Search");
      if (type) {
        appendMenuResult(scope, data);
      } else {
        appendRecipeResult(scope, data);
      }
      searchAjaxd++;
      return void 0;
    },
    error: function(data, status) {
      console.log("[ERROR]search: " + status);
      return void 0;
    }
  });
  return void 0;
};

appendRecipeResult = function(scope, data) {
  var count, html, id, name, rating, recipe, results, url, _i, _len;
  console.log("append recipe for scope: " + scope[0].id);
  if (data.length % 2 && data.length !== 1) {
    data.length--;
  }
  results = scope.find("#Results");
  count = 0;
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    recipe = data[_i];
    html = '';
    id = recipe.recipe_id;
    name = recipe.name;
    rating = recipe.rating;
    url = recipe.smallURL;
    if (count % 2 === 0) {
      html += '<div class="recipe_list_row list_row_left" id="PopularRecipe' + id + '">';
    } else {
      html += '<div class="recipe_list_row list_row_right" id="PopularRecipe' + id + '">';
    }
    html += '<a href="#RecipeContent"><img class="recipe_img" src="' + url + '"></a>';
    html += '<div class="recipe_title">' + name + '</div>';
    html += '<div class="icon star recipe_rating">' + rating + '</div>';
    html += '</div>';
    results.append(html);
    count++;
  }
  results.find("#bottomBar").remove();
  results.append('<div id="bottomBar" style="display:block;height:0;clear:both;">&nbsp;</div>');
  scope.find("#infinite").text("Load More");
  return void 0;
};

appendMenuResult = function(scope, data) {
  var html, id, list, rating, recipe, results, src, title, _i, _j, _len, _len1, _ref;
  console.log("append menu for scope: " + scope[0].id);
  results = scope.find("#Results");
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    list = data[_i];
    html = '';
    id = list.list_id;
    title = list.name;
    rating = list.rating;
    if (rating === 0) {
      rating = 'No rating';
    } else {
      rating += " stars";
    }
    html = '<div class="menu_box" id="KitchenMenu' + id + '">';
    html += '<h2 class="menu_title" style="margin-left:5px;color:black;">' + title + '&nbsp;&nbsp;&nbsp;<i class="icon star">' + rating + '</i>&nbsp;&nbsp;<i class="icon chat">comments</i></h2>';
    html += '<div class="menu_img">';
    _ref = list.recipes;
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      recipe = _ref[_j];
      src = recipe.smallURL;
      html += '<img src="' + src + '" height="20%">';
    }
    html += '</div>';
    html += '<div class="menu_cooking_box"><a class="button red menu_cooking_btn" href="#Cooking">Cook</a><a class="button green" style="float:right;width:20%;margin-right:2%;" href="#Collection">View</a></div><div style="display:inline-block;height:0;width:100%;">&nbsp;</div>';
    html += '</div>';
    results.append(html);
  }
  scope.find("#infinite").text("Load More");
  return void 0;
};

addInfiniteScroll = function() {
  var scrollerList;
  console.log("add infinite-scroll");
  scrollerList = $("#main_Search").scroller();
  scrollerList.clearInfinite();
  scrollerList.addInfinite();
  $.bind(scrollerList, 'infinite-scroll', function() {
    var self;
    console.log("search infinite-scroll");
    self = this;
    $("#main_Search").find("#infinite").text("Loading more...");
    scrollerList.addInfinite();
    clearTimeout(lastId);
    return lastId = setTimeout(function() {
      return $("#SearchBar").trigger("keyup");
    }, 1000);
  });
  return void 0;
};
