// Generated by CoffeeScript 1.7.1
var appendPopularList, getPopular, infiniteScrollCleanUp, lastId, successTriggered;

$(document).ready(function() {
  var scrollerList;
  scrollerList = $('#main_Popular').scroller();
  scrollerList.addInfinite();
  return $.bind(scrollerList, "infinite-scroll", function() {
    var lastId, self;
    console.log("infinite-scroll");
    self = this;
    $("#main_Popular").find("#infinite").text("Loading...");
    scrollerList.addInfinite();
    clearTimeout(lastId);
    lastId = setTimeout(getPopular(successTriggered, self), 3000);
    return void 0;
  });
});

successTriggered = 0;

lastId = -1;

getPopular = function(times, scrollObj) {
  $.ajax({
    type: "GET",
    url: 'http://140.114.195.58:8080/CookIEServer/discover_recipelists',
    dataType: 'jsonp',
    data: {
      'type': 'popular',
      'times': times
    },
    success: function(data) {
      console.log(data);
      return successTriggered++;
    },
    error: function(data) {
      return console.log(data);
    },
    complete: infiniteScrollCleanUp(scrollObj)
  });
  return void 0;
};

infiniteScrollCleanUp = function(scrollObj) {
  console.log("Cleaning up");
  $("#main_Popular").find("#infinite").text("Load More");
  scrollObj.clearInfinite();
  return void 0;
};

appendPopularList = function(data) {
  var html, img, list, menuList, rating, recipe, title, _i, _j, _len, _len1, _ref;
  if (data === null) {
    $("#main_Popular").find("#infinite").text("No more lists");
    return 1;
  }
  menuList = $('#PopularMenuList');
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    list = data[_i];
    title = list.name;
    rating = list.rating;
    if (rating === '0') {
      rating = 'no';
    }
    html = '<div style="background-color:white;margin:5px" >';
    html += '<h3>' + title + '</h3> <i>' + rating + ' stars</i>';
    html += '<div style="float:left; width:100%;background-color:white;">';
    _ref = list.recipes;
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      recipe = _ref[_j];
      img = recipe.img;
    }
    html += '</div>';
    html += '<div style="float:left;width:100%;background-color:white;"><div class="button red" style="float:right">Cook</div></div><div style="display:inline-block;height:0;width:100%;">&nbsp;</div>';
    html += '</div>';
    menuList.append(html);
    html = '';
  }
  return void 0;
};
