// Generated by CoffeeScript 1.7.1
var getPopularMenus, lastId, menuAjaxd;

menuAjaxd = 0;

lastId = -1;

$(document).ready(function() {
  addInfiniteScroll($('#main_Popular_Menus'), 1000, function() {
    return getPopularMenus(menuAjaxd);
  });
  return void 0;
});

getPopularMenus = function(times) {
  $.ajax({
    type: "GET",
    url: 'http://54.178.135.71:8080/CookIEServer/discover_recipelists',
    dataType: 'jsonp',
    crossDomain: true,
    data: {
      'type': 'popular',
      'times': times
    },
    jsonp: false,
    timeout: 10000,
    success: function(data) {
      var scope, scrollerList;
      console.log("[SUCCESS]fetch popular menu");
      console.log(data);
      menuAjaxd++;
      scrollerList = $('#main_Popular_Menus').scroller();
      scrollerList.clearInfinite();
      if (data === null || data.length === 0) {
        $("#main_Popular_Menus").find("#infinite").text("No more menu");
        menuAjaxd--;
        return void 0;
      }
      scope = $("#main_Popular_Menus");
      appendMenuResult(scope, data);
      return void 0;
    },
    error: function(data, status) {
      console.log("[ERROR]fetch popular menu: " + status);
      $("#main_Popular_Menus").find("#infinite").text("Error. Try Again?");
      return void 0;
    }
  });
  return void 0;
};
