// Generated by CoffeeScript 1.7.1
var allCatAjaxd, appendAllCategoryResult, getAllCategory, getSingleCategory, singleCatAjaxd, singleCatId;

singleCatId = 26;

allCatAjaxd = 0;

singleCatAjaxd = 0;

$(document).ready(function() {
  addInfiniteScroll($("#main_AllCategories"), 1000, function() {
    return getAllCategory(allCatAjaxd);
  });
  addInfiniteScroll($("#main_Category"), 1000, function() {
    return getSingleCategory(singleCatAjaxd, singleCatId);
  });
  return void 0;
});

getAllCategory = function(times) {
  $.ajax({
    type: "GET",
    url: "http://54.178.135.71:8080/CookIEServer/discover_category",
    dataType: 'jsonp',
    crossDomain: true,
    data: {
      'times': times
    },
    jsonp: false,
    timeout: 10000,
    success: function(data) {
      var scrollerList;
      console.log("[SUCCESS]fetch categories");
      console.log(data);
      allCatAjaxd++;
      scrollerList = $("#main_AllCategories").scroller();
      scrollerList.clearInfinite();
      if (data.length === 0) {
        $("#main_AllCategories").find("#infinite").text("No more categories");
        allCatAjaxd--;
        return void 0;
      }
      $("#main_AllCategories").find("#infinite").text("Load more");
      appendAllCategoryResult(data);
      return void 0;
    },
    error: function(data) {
      var scrollerList;
      console.log("[ERROR]fetch kitchen menu: " + status);
      scrollerList = $("#main_AllCategories").scroller();
      scrollerList.clearInfinite();
      $("#main_AllCategories").find("#infinite").text("Error. Try Again?");
      return void 0;
    }
  });
  return void 0;
};

appendAllCategoryResult = function(data) {
  var html, id, results, tag, tagGroup, _i, _j, _len, _len1, _ref;
  console.log("append all category result");
  results = $("#main_AllCategories").find("#Results");
  results.find(".new").removeClass("new");
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    tagGroup = data[_i];
    if (tagGroup.tagWithRecipe.length === 0) {
      continue;
    }
    html = '<div class="category_box" id="TagFilter' + tagGroup.tagfilter.filterId + '"><h2 style="margin-left:5px;">' + tagGroup.tagfilter.filterName + '</h2>';
    _ref = tagGroup.tagWithRecipe;
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      tag = _ref[_j];
      id = tag.tag.tagId;
      html += '<div id="Tag' + id + '" class="cat_wrapper new" data-tag-id="' + id + '" data-times="0"><img class="cat_img" src="' + tag.mostPopularRecipe.smallURL + '"><div class="cat_text">' + tag.tag.tagName + '</div></div>';
    }
    html += '</div><div class="divider">&nbsp;</div>';
    results.append(html);
  }
  results.find(".new").forEach(function(elem) {
    return $(elem).click(function() {
      var times;
      $.ui.loadContent("#main_Category");
      times = this.getAttribute('data-times');
      getSingleCategory(times, this.getAttribute('data-tag-id'));
      return this.setAttribute('data-times', times + 1);
    });
  });
  return void 0;
};

getSingleCategory = function(times, tagId) {
  $.ajax({
    type: "GET",
    url: "http://54.178.135.71:8080/CookIEServer/get_tag",
    dataType: 'jsonp',
    crossDomain: true,
    data: {
      'times': times,
      'tag_id': tagId
    },
    jsonp: false,
    timeout: 10000,
    success: function(data) {
      var scope, scrollerList;
      console.log("[SUCCESS]fetch cat #" + tagId);
      console.log(data);
      singleCatAjaxd++;
      scrollerList = $('#main_Category').scroller();
      scrollerList.clearInfinite();
      if (data.length === 0) {
        $("#main_Category").find("#infinite").html("No more recipes.");
        singleCatAjaxd--;
        return void 0;
      }
      $.ui.setTitle(data.tag.tagName);
      scope = $('#main_Category');
      scope.find("#Results").html("");
      appendRecipeResult(scope, data.recipes);
      return void 0;
    },
    error: function(data, status) {
      console.log("[ERROR]fetch cat #" + tagId);
      $("#main_Category").find("#infinite").html("Error. Try Again?");
      return void 0;
    }
  });
  return void 0;
};
