// Generated by CoffeeScript 1.7.1
var appendKitchenMenuList, getKitchenMenus, lastId, menuAjaxd;

menuAjaxd = 0;

lastId = -1;

$(document).ready(function() {
  var scrollerList;
  scrollerList = $('#main_Kitchen_Menus').scroller();
  scrollerList.addInfinite();
  $.bind(scrollerList, "infinite-scroll", function() {
    var self;
    console.log("kitchen menu infinite-scroll");
    self = this;
    $("#main_Kitchen_Menus").find("#infinite").text("Loading...");
    scrollerList.addInfinite();
    clearTimeout(lastId);
    lastId = setTimeout(function() {
      return getKitchenMenus(menuAjaxd, self);
    }, 1000);
    return void 0;
  });
  return void 0;
});

getKitchenMenus = function(times, scrollObj) {
  $.ajax({
    type: "GET",
    url: 'http://140.114.195.58:8080/CookIEServer/discover_recipelists',
    dataType: 'jsonp',
    crossDomain: true,
    data: {
      'type': 'popular',
      'times': times
    },
    jsonp: false,
    timeout: 10000,
    success: function(data) {
      console.log("[SUCCESS]fetch kitchen menu");
      console.log(data);
      appendKitchenMenuList(data, scrollObj);
      menuAjaxd++;
      return void 0;
    },
    error: function(data, status) {
      console.log("[ERROR]fetch kitchen menu: " + status);
      $("#main_Kitchen_Menus").find("#infinite").text("Load More");
      scrollObj.clearInfinite();
      return void 0;
    }
  });
  return void 0;
};

appendKitchenMenuList = function(data, scrollObj) {
  var html, id, list, menuList, rating, recipe, src, title, _i, _j, _len, _len1, _ref;
  if (data.length === 0) {
    $("#main_Kitchen_Menus").find("#infinite").text("No more lists");
    scrollObj.clearInfinite();
    menuAjaxd--;
    return 1;
  }
  menuList = $('#KitchenMenuList');
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    list = data[_i];
    html = '';
    id = list.list_id;
    title = list.name;
    rating = list.rating;
    html = '<div class="menu_box" id="KitchenMenu' + id + '">';
    html += '<h2 class="menu_title">' + title + '</h2>&nbsp;&nbsp;&nbsp;<i class="icon star">' + rating + ' stars</i>&nbsp;&nbsp;<i class="icon chat">comments</i>';
    html += '<div class="menu_img">';
    _ref = list.recipes;
    for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
      recipe = _ref[_j];
      src = recipe.imageUrl;
      src = 'img/love.jpg';
      html += '<img src="' + src + '" height="20%">';
    }
    html += '</div>';
    html += '<div class="menu_cooking_box"><a class="button red menu_cooking_btn" href="#Cooking">Cook</a></div><div style="display:inline-block;height:0;width:100%;">&nbsp;</div>';
    html += '</div>';
    menuList.append(html);
  }
  $("#main_Kitchen_Menus").find("#infinite").text("Load More");
  scrollObj.clearInfinite();
  return void 0;
};
