// Generated by CoffeeScript 1.7.1
var getMenuContent, loadMenuContent;

getMenuContent = function(scope, menuId) {
  scope.find("#Results").hide();
  scope.find("#Loading").show();
  console.log("fetch menu#" + menuId);
  $.ajax({
    type: 'GET',
    url: 'http://54.178.135.71:8080/CookIEServer/recipelist',
    dataType: 'application/json',
    data: {
      'list_id': menuId
    },
    timeout: 10000,
    success: function(data) {
      data = JSON.parse(data);
      console.log("[SUCCESS]fetch menu #" + menuId);
      console.log(data);
      setTimeout(loadMenuContent(scope, data), 1000);
      return void 0;
    },
    error: function(data, status) {
      console.log("[ERROR]fetch recipe #" + recipeId);
      console.log(data);
      return void 0;
    }
  });
  return void 0;
};

loadMenuContent = function(scope, menu) {
  var html, imgHolder, ingredient, ingredientList, recipe, _i, _j, _len, _len1, _ref, _ref1;
  console.log("load for scope: " + scope[0].id);
  $.ui.setTitle(menu.listName);
  imgHolder = scope.find(".menuContent_imgHolder");
  imgHolder.html("");
  _ref = menu.recipes;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    recipe = _ref[_i];
    html = '<div class="menuContent_imgWrapper_left">';
    html += '<div class="menuContent_imgText_left">' + recipe.name + '</div>';
    html += '<img class="menuContent_img" src="' + recipe.smallURL + '">';
    html += '</div>';
    imgHolder.append(html);
  }
  if (menu.rating === 0) {
    menu.rating = 'No rating';
  }
  scope.find("#MenuRating").html(menu.rating);
  scope.find("#MenuByUser").html("By: " + menu.userName);
  scope.find("#MenuTime").html("Time: " + menu.costTime);
  scope.find("#MenuDescription").html(menu.description);
  ingredientList = scope.find("#MenuIngredientList");
  ingredientList.html("");
  _ref1 = menu.ingList;
  for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
    ingredient = _ref1[_j];
    html = '<li>' + ingredient.ingredientName + " .............. " + ingredient.amount + " " + ingredient.unitName;
    ingredientList.append(html);
  }
  scope.find("#Loading").hide();
  scope.find("#Results").show();
  return void 0;
};
