// Generated by CoffeeScript 1.7.1
var getPopular;

$(document).ready(function() {
  var scrollerList;
  scrollerList = $('#main_Popular').scroller();
  scrollerList.addInfinite();
  return $.bind(scrollerList, "infinite-scroll", function() {
    var self;
    console.log("infinite-scroll");
    self = this;
    $("#main_Popular").find("#infinite").text("Loading...");
    scrollerList.addInfinite();
    return setTimeout(function() {
      $("#main_Popular").find("#infinite").text("Load More");
      $("#PopularMenuList").append("<div>...This text was added via infinite scroll</div>");
      return self.clearInfinite();
    }, 3000);
  });
});

getPopular = function(times) {
  var opt;
  opt = {
    type: "GET",
    url: '/ajaxTest.html',
    data: {
      'type': 'popular',
      'times': times
    },
    success: function(data) {
      return console.log(data);
    },
    error: function(data) {
      return console.log(data);
    }
  };
  return $.ajax(opts);
};
