// Generated by CoffeeScript 1.7.1
var appendPopularRecipe, getPopularRecipe, lastId, recipeAjaxd;

$(document).ready(function() {
  var scrollerList;
  scrollerList = $('#main_Popular_Recipes').scroller();
  scrollerList.addInfinite();
  return $.bind(scrollerList, "infinite-scroll", function() {
    var lastId, self;
    console.log("recipe infinite-scroll");
    self = this;
    $("#main_Popular_Recipes").find("#infinite").text("Loading...");
    scrollerList.addInfinite();
    clearTimeout(lastId);
    lastId = setTimeout(function() {
      return getPopularRecipe(recipeAjaxd, self);
    }, 1000);
    return void 0;
  });
});

recipeAjaxd = 0;

lastId = -1;

getPopularRecipe = function(times, scrollObj) {
  $.ajax({
    type: "GET",
    url: 'http://140.114.195.58:8080/CookIEServer/discover_recipes',
    dataType: 'jsonp',
    crossDomain: true,
    data: {
      'type': 'popular',
      'times': times
    },
    jsonp: false,
    success: function(data) {
      console.log("success");
      console.log(data);
      appendPopularRecipe(data, scrollObj);
      recipeAjaxd++;
      return void 0;
    },
    error: function(data, status) {
      console.log("error" + status);
      console.log(data);
      return void 0;
    }
  });
  return void 0;
};

appendPopularRecipe = function(data, scrollObj) {
  var count, html, id, recipe, recipeList, url, _i, _len;
  if (data.length === 0) {
    $("#main_Popular_Recipes").find("#infinite").text("No more lists");
    scrollObj.clearInfinite();
    recipeAjaxd--;
    return 1;
  }
  if (data.length % 2) {
    data.length--;
  }
  recipeList = $('#PopularRecipeList');
  count = 0;
  html = '<div style="position: relative; float: left; width: 100%; border: solid 1px #000">';
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    recipe = data[_i];
    id = recipe.recipe_id;
    url = recipe.imageUrl;
    url = 'img/love.jpg';
    html += '<img id="PopularRecipe' + id + '"src="' + url + '" style="float: left; width:50%;">';
    if (count === data.length - 1) {
      html += '</div><div class="divider">&nbsp; </div>';
      recipeList.append(html);
      html = '';
    } else if (count % 2) {
      html += '</div><div class="divider"> &nbsp;</div><div style="position: relative; float: left; width: 100%; border: solid 1px #000">';
      recipeList.append(html);
      html = '';
    }
    count++;
  }
  $("#main_Popular_Recipes").find("#infinite").text("Load More");
  scrollObj.clearInfinite();
  return void 0;
};
