// Generated by CoffeeScript 1.7.1

/* Class Definitions */
var Step, cookingStarted, loadStep;

Step = (function() {
  function Step(startTime, duration, percentage, digest) {
    this.startTime = startTime;
    this.duration = duration;
    this.percentage = percentage;
    this.digest = digest;
    this.endTime = this.startTime + this.duration;
    void 0;
  }

  Step.calculatePercentage = function(currentTime) {
    return Math.ceil((this.endTime - currentTime) / this.duration * 100);
  };

  return Step;

})();


/* Function definitions */

cookingStarted = function() {
  var cookingData, currentStep, finishPercentage;
  if (window.cookingData === void 0) {
    return void 0;
  }
  cookingData = window.cookingData;
  currentStep = window.currentStep;
  finishPercentage = Math.ceil(currentStep / cookingData.steps.length * 100);
  console.log("cooking started");
  $.ui.setTitle("Step " + currentStep + " (" + finishPercentage + "%)");
  return loadStep(currentStep);
};

loadStep = function(currentStep) {
  var nextStep, scope, thisStep;
  console.log("load step#" + currentStep);
  thisStep = window.cookingData.steps[currentStep];
  scope = $("#Step");
  scope.find(".this_step_recipe_name").html(thisStep.recipeName);
  if (thisStep.imageURL !== void 0) {
    console.log("img");
    scope.find(".this_step_img").attr("src", thisStep.imageURL);
    scope.find(".this_step_img_wrapper").show();
  } else {
    console.log("no img");
    scope.find(".this_step_img_wrapper").hide();
  }
  scope.find(".this_step_digest").html(thisStep.digest);
  nextStep = window.cookingData.steps[currentStep + 1];
  scope.find(".next_step_name").html(nextStep.stepName);
  return scope.find(".next_step_time").html(nextStep.time);
};
