// Generated by CoffeeScript 1.7.1
var utilityDetect, utilityEdit, utilityTrash;

$(document).ready(function() {
  $("body").find(".popup_btn").forEach(function(elem) {
    return $(elem).click(function() {
      return utilityDetect(this);
    });
  });
  return void 0;
});

utilityDetect = function(elem) {
  console.log("Popup #" + elem.id);
  switch (elem.getAttribute('data-function')) {
    case "edit":
      utilityEdit();
      break;
    case "trash":
      utilityTrash();
      break;
    default:
      break;
  }
  return void 0;
};

utilityEdit = function() {
  console.log('popup edit');
  return void 0;
};

utilityTrash = function() {
  console.log('popup trash');
  return void 0;
};
