// Generated by CoffeeScript 1.7.1
var findChosenRecipeId, resetUtilBtn, utilityDetect, utilityEdit, utilityTrash;

$(document).ready(function() {
  $('body').find('.popup_btn').forEach(function(elem) {
    return $(elem).click(function() {
      return utilityDetect(this);
    });
  });
  return void 0;
});

utilityDetect = function(elem) {
  console.log('Popup #' + elem.id);
  switch (elem.getAttribute('data-function')) {
    case 'edit':
      $('#popup_btn_trash').removeClass('selected');
      $(elem).toggleClass('selected');
      if ($(elem).hasClass('selected')) {
        utilityEdit();
      } else {
        resetUtilBtn();
      }
      break;
    case 'trash':
      $('#popup_btn_edit').removeClass('selected');
      $(elem).toggleClass('selected');
      if ($(elem).hasClass('selected')) {
        utilityTrash();
      } else {
        resetUtilBtn();
      }
      break;
    default:
      break;
  }
  return void 0;
};

resetUtilBtn = function() {
  var utilBtn;
  $('#main_Kitchen_Recipes').find('.selected').removeClass('selected');
  utilBtn = $('#kitchenUtilityBtn');
  utilBtn.removeClass('trash');
  utilBtn.removeClass('edit');
  utilBtn.unbind('click');
  utilBtn.html('Tap on the Cog to begin.');
  return window.mode = 0;
};

utilityEdit = function() {
  var utilBtn;
  console.log('popup edit');
  window.mode = 1;
  utilBtn = $('#kitchenUtilityBtn');
  utilBtn.removeClass('trash');
  utilBtn.addClass('edit');
  utilBtn.html('Start Cooking.');
  utilBtn.click(function() {
    var selectedId;
    return selectedId = findChosenRecipeId();
  });
  return void 0;
};

utilityTrash = function() {
  var utilBtn;
  console.log('popup trash');
  window.mode = 1;
  utilBtn = $('#kitchenUtilityBtn');
  utilBtn.removeClass('edit');
  utilBtn.addClass('trash');
  utilBtn.html('Delete selected recipe.');
  utilBtn.click(function() {
    var ans, data, selectedId;
    ans = confirm("Deleteing recipes from Kitchen. Are you sure?");
    if (ans === false) {
      return void 0;
    }
    selectedId = findChosenRecipeId();
    data = {
      'type': 'recipe',
      'recipe_id': selectedId
    };
    console.log(data);
    $.ajax({
      type: 'DELETE',
      url: 'http://54.178.135.71:8080/CookIEServer/favorite',
      dataType: 'application/json',
      data: data,
      timeout: 10000,
      success: function(data) {
        data = JSON.parse(data);
        console.log("[SUCCESS] deleting recipes #" + selectedId);
        console.log(data);
        return void 0;
      },
      error: function(data, status) {
        console.log("[ERROR] deleting recipes #" + selectedId);
        console.log(data);
        return void 0;
      }
    });
    return void 0;
  });
  return void 0;
};

findChosenRecipeId = function() {
  var recipeSelectedId;
  recipeSelectedId = [];
  $('#main_Kitchen_Recipes').find('.chosen').forEach(function(elem) {
    return recipeSelectedId.push(elem.getAttribute('data-recipe-id'));
  });
  console.log(recipeSelectedId);
  return recipeSelectedId;
};
